# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Etch-a-Sketch 2025!!
tagline: Coordinated Work - Coordinate GitSpace!
description:  Cognition, Action, and Perception People from all over - studying how people behave in the world. 
author: CTA & Others 
baseurl: '/EtchSketch-2025' # the subpath of your site - goes after domain name annandct.github.io/BLOG/.... - #leave blank
url: 'https://annandct.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "_default_pages"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.10.1
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  CAP Lab:
    - https://www.artsci.uc.edu/natural-sciences/psychology/academic-programs/phd/phd-program-tracks-and-emphasis-areas/behavioral-science-track/experimental.html
  Colin @ Teaching Stats and Science:
    - 'https://colinannand.github.io'
  Francis @ Human Agility Lab:
    - https://sites.northwestern.edu/agilitylab/

footer_content:

# Collections for website data
collections:
  staffers:
  experiments:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: experiments
    values:
      layout: experiment
#  - scope:
#      path: ''
#      type: schedules
#    values:
#      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true
